# Docker Compose file for localhost development

services:
  postgresdb:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./init_databases.sql:/docker-entrypoint-initdb.d/10_init_databases.sql
      - ./global_database.sql:/docker-entrypoint-initdb.d/20_global_database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloakauth:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloakauth
    ports:
      # - "8080:8080"
      - "8443:8443"  # HTTPS endpoint
      - "9000:9000"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgresdb
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: 1234
      KC_HEALTH_ENABLED: true
      KC_IMPORT: /opt/keycloak/data/import/test-realm.json
      # SSL
      KC_HTTPS_PORT: 8443
      KC_HTTPS_KEY_STORE_FILE: /opt/keycloak/conf/certificates/keycloak.p12
      KC_HTTPS_KEY_STORE_PASSWORD: changeit
      KC_HTTP_ENABLED: false  # Disable HTTP completely
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: false
    volumes:
      - ./test-realm.json:/opt/keycloak/data/import/test-realm.json
      - ./keycloak/certs:/opt/keycloak/conf/certificates
    command:
      - start # start-dev
      - --import-realm
      - --verbose
    depends_on:
      postgresdb:
        condition: service_healthy

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5001:5001"
    environment:
      # ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://*:5001
      KeyCloak__api_url: "http://keycloakauth:8080/"
      KeyCloak__admin_base: "/admin/realms"
      KeyCloak__url: "keycloakauth:8080"
      realms: "customer1"
      database__realm_url: "Host=postgresdb:5432;User Id=postgres;Password=password"
      database__global_url: "Host=postgresdb:5432;User Id=postgres;Password=password;Database=global"
      eventHandler__api_url: "http://deviceeventhandler:5002/api/DeviceEventHandler/event"

  deviceeventhandler:
    build:
      context: ./DeviceEventHandler
      dockerfile: Dockerfile
    container_name: deviceeventhandler
    ports:
      - "5002:5002"
    environment:
      # ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://*:5002
      backend__api_url: "http://backend:5001/"

  appgw:
    build:
      context: ./AppGW
      dockerfile: Dockerfile
    container_name: appgw
    ports:
      - "80:80"
      - "443:443"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"

volumes:
  timescaledb_data:
